

export const THEMES = [
  {
    id: "0b083919-06b9-484e-9f3b-8abaa0aea02d",
    name: 'rEFInd-minimal',
    description: 'A stunningly clean theme for the rEFInd UEFI boot manager.',
    link: 'https://github.com/evanpurkhiser/rEFInd-minimal',
    user: 'evanpurkhiser',
    user_url: 'https://github.com/evanpurkhiser',
    image: "/images/minimal.webp",
    multipleBackgrounds:false
  },
  {
    id: "703a593a-bfe7-4a90-b802-9ac8d960ac34",
    name: 'rEFInd-theme-Regular',
    description: 'A simplistic clean and minimal theme for rEFInd',
    link: 'https://github.com/bobafetthotmail/refind-theme-regular',
    user: 'bobafetthotmail',
    user_url: 'https://github.com/bobafetthotmail',
    image:'/images/regular.webp',
    multipleBackgrounds:true
  },
  {
    id: "b3ef8306-fadd-406e-98fb-0885c8439284",
    name: 'refind-ambience',
    description: 'Minimal theme for the rEFInd boot manager',
    link: 'https://github.com/lukechilds/refind-ambience',
    user: 'lukechilds',
    user_url: 'https://github.com/lukechilds',
    image:'/images/ambience.webp',
    multipleBackgrounds:false
  },
  {
    id: "c0e3b99a-c604-4505-88c9-ee9803fbc6de",
    name: 'ursamajor-rEFInd',
    description: 'Ursa Major theme for rEFInd Bootloader',
    link: 'https://github.com/kgoettler/ursamajor-rEFInd',
    user: 'kgoettler',
    user_url: 'https://github.com/kgoettler',
    image: '/images/ursa.webp',
    multipleBackgrounds:false
  },
  {
    id: "f90fd842-8086-4217-abb5-3faf2969d159",
    name: 'rEFInd-glassy',
    description: 'A minimalistic rEFInd theme',
    link: 'https://github.com/Pr0cella/rEFInd-glassy',
    user: 'Pr0cella',
    user_url: 'https://github.com/Pr0cella',
    image:'/images/glassy.webp',
    multipleBackgrounds:false
  },
  {
    id: "31f782d9-bb59-4404-9062-bca2f779fa20",
    name: 'darkmini',
    description: 'Dark theme for rEFInd',
    link: 'https://github.com/LightAir/darkmini',
    user: 'LightAir',
    user_url: 'https://github.com/LightAir',
    image:'/images/darkmini.webp',
    multipleBackgrounds:true
  },
  {
    id: "a035029e-c48a-499e-af88-4d362a474ca8",
    name: 'Matrix-rEFInd',
    description: 'A rEFInd theme based on the scene from the movie Matrix where Morpheus offers the two pills to Neo',
    link: 'https://github.com/Yannis4444/Matrix-rEFInd',
    user: 'Yannis4444',
    user_url: 'https://github.com/Yannis4444',
    image:'/images/matrix.webp',
    multipleBackgrounds:false
  },
  {
    id: "9934ec8f-894b-425d-a9e5-e668476b6eb3",
    name: 'refind2k',
    description: 'A minimalist dark theme for rEFInd. 💠💻',
    link: 'https://github.com/2KAbhishek/refind2k',
    user: '2KAbhishek',
    user_url: 'https://github.com/2KAbhishek',
    image:'/images/refind2k.webp',
    multipleBackgrounds:true
  },
  {
    id: "2f93363d-1467-4884-b1dd-7b3d9bc7665b",
    name: 'rEFInd-minimal-themes',
    description: 'Minimalist themes for the rEFInd UEFI boot manager.',
    link: 'https://github.com/quantrancse/rEFInd-minimal-themes',
    user: 'quantrancse',
    user_url: 'https://github.com/quantrancse',
    image:'/images/minimal-themes.webp',
    multipleBackgrounds:true,
  },
  {
    id: "4c994c94-e3a8-48a5-8a36-a30c62bccc3f",
    name: 'refind-theme-dark',
    description: '🎨 A simple, dark theme for rEFInd',
    link: 'https://github.com/samuelmeuli/refind-theme-dark',
    user: 'samuelmeuli',
    user_url: 'https://github.com/samuelmeuli',
    image:'/images/refind-theme-dark.webp',
    multipleBackgrounds:false,
  },
  {
    id: "7d3ed7c6-ad88-4587-a580-6207dc204be2",
    name: 'refind',
    description: '🔄 Soothing pastel theme for rEFInd',
    link: 'https://github.com/catppuccin/refind',
    user: 'catppuccin',
    user_url: 'https://github.com/catppuccin',
    image:'/images/refind.webp',
    multipleBackgrounds:false,
  },
  {
    id: "3f3bae4c-ea3c-4797-9907-ae3dbb80802f",
    name: 'rEFInd-chalkboard',
    description: 'A simple monochrome theme for the rEFInd UEFI boot manager',
    link: 'https://github.com/AliciaTransmuted/rEFInd-chalkboard',
    user: 'AliciaTransmuted',
    user_url: 'https://github.com/AliciaTransmuted',
    image:'/images/chalkboard.webp',
    multipleBackgrounds:false,
  },
  {
    id: "8997be74-644f-44ef-a651-8488963d53bb",
    name: 'dm',
    description: 'dm. A theme for rEFInd.',
    link: 'https://github.com/mustaqimM/dm',
    user: 'mustaqimM',
    user_url: 'https://github.com/mustaqimM',
    image:'/images/dm.webp',
    multipleBackgrounds:false,
  },
  {
    id: "29c141df-9489-47e6-9acb-5346f2dd59db",
    name: 'refind-efifetch',
    description: 'neofetch theme for the rEFInd boot manager',
    link: 'https://github.com/bushtail/refind-efifetch',
    user: 'bushtail',
    user_url: 'https://github.com/bushtail',
    image:'/images/efifetch.webp',
    multipleBackgrounds:false,
  },
  {
    id: "17dee397-b823-4811-9f1a-62073335e939",
    name: 'refind-theme-nord',
    description: 'rEFInd theme inspired by the Nord palette',
    link: 'https://github.com/jaltuna/refind-theme-nord',
    user: 'jaltuna',
    user_url: 'https://github.com/jaltuna',
    image:'/images/refind-theme-nord.webp',
    multipleBackgrounds:false,
  },
  {
    id: "03c63459-09d4-4227-8536-3195265724c0",
    name: 'rEFInd-theme',
    description: 'A boot manager theme for rEFInd',
    link: 'https://github.com/hashhar/rEFInd-theme',
    user: 'hashhar',
    user_url: 'https://github.com/hashhar',
    image:'/images/refind-theme.webp',
    multipleBackgrounds:true,
  },
  {
    id: "1e7f4055-8787-45ed-b516-0551a6d785ae",
    name: 'refind-bsd-black',
    description: 'A black rEFInd BSD icon theme for DragonFlyBSD, FreeBSD, GhostBSD, MidnightBSD, NetBSD, NomadBSD and OpenBSD.',
    link: 'https://github.com/indgy/refind-bsd-black',
    user: 'indgy',
    user_url: 'https://github.com/indgy',
    image:'/images/bsd-black.webp',
    multipleBackgrounds:false,
  },
  {
    id: "e73827f0-4dbc-4280-9f5d-04d43c212729",
    name: 'refind-theme-elementary',
    description: 'an elementary theme for rEFInd',
    link: 'https://github.com/danirabbit/refind-theme-elementary',
    user: 'danirabbit',
    user_url: 'https://github.com/danirabbit',
    image:'/images/elementary.webp',
    multipleBackgrounds:false,
  },
  {
    id: "2058d72b-c3b7-4667-8e42-0afc743b9e32",
    name: 'rEFInd-minimal-modded',
    description: 'Minimal rEFInd theme.',
    link: 'https://github.com/AdityaGarg8/rEFInd-minimal-modded',
    user: 'AdityaGarg8',
    user_url: 'https://github.com/AdityaGarg8',
    image:'/images/minimal-modded.webp',
    multipleBackgrounds:false,
  },
  {
    id: "289ede6d-e144-4ea3-9a4a-6fde04feb962",
    name: 'rEFInd-indulgence',
    description: 'rEFInd-indulgence is a luxurious soft leather icon theme with a custom hand stitched font for the rEFInd UEFI boot manager',
    link: 'https://github.com/AliciaTransmuted/rEFInd-indulgence',
    user: 'AliciaTransmuted',
    user_url: 'https://github.com/AliciaTransmuted',
    image:'/images/indulgence.webp',
    multipleBackgrounds:false,
  },
  {
    id: "08680640-f0cb-4fa4-9e3b-452793ec7959",
    name: 'rEFInd-minimal-drunkcj',
    description: 'rEFInd is an easy to use boot manager for UEFI based systems. This is a clean and minimal theme for it.',
    link: 'https://github.com/drunckj/rEFInd-minimal-drunkcj',
    user: 'drunckj',
    user_url: 'https://github.com/drunckj',
    image:'/images/minimal-drunkcj.webp',
    multipleBackgrounds:false,
  },
  {
    id: "df33a6c9-d9cd-4685-ac8f-0e834ae62076",
    name: 'Refind-Maia-Reskin',
    description: 'My take on the Refind Maia theme.',
    link: 'https://github.com/Fantailed/Refind-Maia-Reskin',
    user: 'Fantailed',
    user_url: 'https://github.com/Fantailed',
    image:'/images/maia-reskin.webp',
    multipleBackgrounds:false,
  },
  {
    id: "d2830132-434c-4f4a-97c8-63707e1835e2",
    name: 'glow',
    description: 'Glow theme for the rEFInd boot manager',
    link: 'https://github.com/antsif-a/glow',
    user: 'antsif-a',
    user_url: 'https://github.com/antsif-a',
    image:'/images/glow.webp',
    multipleBackgrounds:false,
  },
  {
    id: "b9674c05-7561-4f04-aa27-1dcea7889ce6",
    name: 'Refind-theme-Fluent-dark',
    description: 'Fluent Theme for rEFInd',
    link: 'https://github.com/voduong404/Refind-theme-Fluent-dark',
    user: 'voduong404',
    user_url: 'https://github.com/voduong404',
    image:'/images/fluent-dark.webp',
    multipleBackgrounds:false,
  },
  {
    id: "da4acdf2-291b-458e-ab60-fb2751fb13d6",
    name: 'refind-material-theme',
    description: 'Material Theme for rEFInd; with scripts used to generate it.',
    link: 'https://github.com/Patricol/refind-material-theme',
    user: 'Patricol',
    user_url: 'https://github.com/Patricol',
    image:'/images/material.webp',
    multipleBackgrounds:false,
  },
  {
    id: "9a166446-0454-4719-b419-1ca491ede647",
    name: 'rEFInd-details',
    description: 'A colourful theme for the rEFInd UEFI boot manager',
    link: 'https://github.com/AliciaTransmuted/rEFInd-details',
    user: 'AliciaTransmuted',
    user_url: 'https://github.com/AliciaTransmuted',
    image:'/images/details.webp',
    multipleBackgrounds:false,
  },
  {
    id: "96633c9e-f09c-4fa1-892a-32e9b0ad1f95",
    name: 'custom-bootloader',
    description: 'My personal bootloader configuration and resource files',
    link: 'https://github.com/tedski999/custom-bootloader',
    user: 'tedski999',
    user_url: 'https://github.com/tedski999',
    image:'/images/bootloader.webp',
    multipleBackgrounds:false,
  },
  {
    id: "44a08806-bc16-4598-81a0-f87cb83ff888",
    name: 'rEFInd-minimal-dark',
    description: 'rEFInd is a simplistic boot manager for UEFI based systems. This is a dark, clean, minimal theme for it.',
    link: 'https://github.com/PillTime/rEFInd-minimal-dark',
    user: 'PillTime',
    user_url: 'https://github.com/PillTime',
    image:"/images/minimal-dark.webp",
    multipleBackgrounds:false,
  },
  {
    id: "1656f08a-8c46-48a0-afc0-12509c47e37d",
    name: 'refind-theme-regular',
    description: 'A simplistic clean and minimal theme for rEFInd',
    link: 'https://github.com/noraj/refind-theme-regular',
    user: 'noraj',
    user_url: 'https://github.com/noraj',
    image:"/images/regular2.webp",
    multipleBackgrounds:true,
  },
  {
    id: "9ba9ab2c-ba60-43fa-a545-155ee340f052",
    name: 'rEFInd-theme-Yours',
    description: "Y-o-u-r-s, Your own usual rEFInd's sign. You can set your profile, device and your name. Yours is based on rEFInd, with grubfm built-in.",
    link: 'https://github.com/M-L-P/rEFInd-theme-Yours?tab=readme-ov-file',
    user: 'M-L-P',
    user_url: 'https://github.com/M-L-P',
    image:"/images/yours.webp",
    multipleBackgrounds:false,
  },
  {
    id: "79010bb7-c13c-4fc9-9940-5b0c85d72551",
    name: 'refind-ambience-deer-and-fireflies',
    description: "A simple and minimalist theme for the rEFInd boot loader",
    link: 'https://github.com/jpmvferreira/refind-ambience-deer-and-fireflies',
    user: 'jpmvferreira',
    user_url: 'https://github.com/jpmvferreira',
    image:"/images/deer-and-fireflies.webp",
    multipleBackgrounds:false,
  },
  {
    id: "aab90372-b2bc-4502-a2c7-a7379bc41718",
    name: 'refind-gruvbox-theme',
    description: "Theme for rEFInd based on Gruvbox color scheme",
    link: 'https://github.com/sihann/refind-gruvbox-theme',
    user: 'sihann',
    user_url: 'https://github.com/sihann',
    image:"/images/gruvbox.webp",
    multipleBackgrounds:false,
  },
  {
    id: "5705ce00-a18e-4547-b6a3-a83dd487f21d",
    name: 'rEFInd-mountain',
    description: "A clean mountain theme for the rEFInd UEFI boot manager.",
    link: 'https://github.com/Chrisae9/rEFInd-mountain',
    user: 'Chrisae9',
    user_url: 'https://github.com/Chrisae9',
    image:"/images/mountain.webp",
    multipleBackgrounds:false,
  },
  {
    id: "d092957a-171f-45d0-bc84-fc2c019b987e",
    name: 'refind-theme-regular',
    description: "A simplistic clean and minimal theme for rEFInd",
    link: 'https://github.com/1j01/refind-theme-regular',
    user: '1j01',
    user_url: 'https://github.com/1j01',
    image:"/images/regular3.webp",
    multipleBackgrounds:false,
  },
  {
    id: "3bb70c91-88f8-4b7a-8fc5-c589a7ec2147e",
    name: 'hi-themes-refind',
    description: "Multi-themes for refined",
    link: 'https://github.com/SLywnow/hi-themes-refind',
    user: 'SLywnow',
    user_url: 'https://github.com/SLywnow',
    image:"/images/hi.webp",
    multipleBackgrounds:true,
  },
  {
    id: "195b8308-278f-4f92-8909-156b7818d977",
    name: 'linux-boot-efi',
    description: "rEFInd theme, systemd-boot, mkinitcpio, dracut, plymouth, sddm, wallpapers, color-schemes, nvidia, amdgpu",
    link: 'https://github.com/Valeria-Fadeeva/linux-boot-efi',
    user: 'Valeria-Fadeeva',
    user_url: 'https://github.com/Valeria-Fadeeva',
    image:"/images/boot.webp",
    multipleBackgrounds:true,
  },
  {
    id: "f685ee46-9e01-41bc-bfba-e986aaa82935",
    name: 'grey-apple',
    description: "rEFInd theme inspired by apple boot screen",
    link: 'https://github.com/matomatical/grey-apple',
    user: 'matomatical',
    user_url: 'https://github.com/matomatical',
    image:"/images/apple.webp",
    multipleBackgrounds:false,
  },
  {
    id: "838d9645-fabf-40bc-a68b-7fe4267275da",
    name: 'LazaGRUB',
    description: "Una GRUB hecha en rEFInd basada en Lazaro©™",
    link: 'https://github.com/FerLS/LazaGRUB',
    user: 'FerLS',
    user_url: 'https://github.com/FerLS',
    image:"/images/laza.webp",
    multipleBackgrounds:false,
  },
  {
    id: "e77e90f6-db6b-4836-b22f-710a3454b00d",
    name: 'rEFInd-dawn',
    description: "A rEFInd theme",
    link: 'https://github.com/ajlende/rEFInd-dawn',
    user: 'ajlende',
    user_url: 'https://github.com/ajlende',
    image:"/images/dawn.webp",
    multipleBackgrounds:false,
  },
  {
    id: "9b82d262-30af-4ec6-ae14-bfcfdd3262b3",
    name: 'rEFInd-pachirisu',
    description: "Pachirisu theme for the rEFInd boot manager",
    link: 'https://github.com/zeroday0619/rEFInd-pachirisu',
    user: 'zeroday0619',
    user_url: 'https://github.com/zeroday0619',
    image:"/images/pachirisu.webp",
    multipleBackgrounds:false,
  },
  {
    id: "79a47d4f-d2a7-4b45-897c-e3bb3e19932e",
    name: 'rEFInd-Celestial-Theme',
    description: "A modern, colorful Theme for the rEFInd Bootmanager (Theme by Paradox1937)",
    link: 'https://github.com/Paradox1937/rEFInd-Celestial-Theme',
    user: 'Paradox1937',
    user_url: 'https://github.com/Paradox1937',
    image:"/images/celestial.webp",
    multipleBackgrounds:false,
  },
  {
    id: "75502120-5d7e-4783-96c6-1cd50207af9b",
    name: 'terminal-bootloader',
    description: "my personal bootloader theme",
    link: 'https://github.com/phonot/terminal-bootloader',
    user: 'phonot',
    user_url: 'https://github.com/phonot',
    image:"/images/terminal.webp",
    multipleBackgrounds:false,
  },
  {
    id: "0ff445ff-0128-4737-b8e1-5cbc5a4afe49",
    name: 'rEFInd-RetroGame',
    description: "A Retro Game inspired theme for rEFInd Boot Manager. This theme will surely make you reminisce about the yesteryears of Retro Gaming and Pixelated Sprite graphics.",
    link: 'https://github.com/riftsandroses/rEFInd-RetroGame',
    user: 'riftsandroses',
    user_url: 'https://github.com/riftsandroses',
    image:"/images/retrogame.webp",
    multipleBackgrounds:false,
  },
  {
    id: "af7ddcf8-088d-4e28-9cf0-c6ef7731dfdc",
    name: 'BlackCatMuzzle-rEFInd',
    description: "rEFInd is a simplistic boot manager for UEFI-based systems. This is a clean, dark and cute theme for it.",
    link: 'https://github.com/Scorpi-ON/BlackCatMuzzle-rEFInd',
    user: 'Scorpi-ON',
    user_url: 'https://github.com/Scorpi-ON',
    image:"/images/blackcatmuzzle.webp",
    multipleBackgrounds:true,
  },
  {
    id: "08e8e984-f86c-4f41-bc91-8194667b42fb",
    name: 'rEFInd-wildside',
    description: "rEFInd-wildside is a shiny black background with bold red 3d icon theme for the rEFInd UEFI Boot Manager.",
    link: 'https://github.com/AliciaTransmuted/rEFInd-wildside',
    user: 'AliciaTransmuted',
    user_url: 'https://github.com/AliciaTransmuted',
    image:"/images/wildside.webp",
    multipleBackgrounds:false,
  },
  {
    id: "d9854149-a771-43ef-b913-9613f2b3258d",
    name: 'rEFInd-splash',
    description: "rEFInd-splash is a swimming pool theme with colourful pool toy icons for the rEFInd UEFI Boot Manager",
    link: 'https://github.com/AliciaTransmuted/rEFInd-splash',
    user: 'AliciaTransmuted',
    user_url: 'https://github.com/AliciaTransmuted',
    image:"/images/splash.webp",
    multipleBackgrounds:false,
  },
  {
    id: "c2fec1bf-f71b-409e-b867-2691df61204a",
    name: 'hi-dark',
    description: "A little test dark theme, based on https://github.com/dheishman/refind-dreary",
    link: 'https://github.com/SLywnow/hi-dark',
    user: 'SLywnow',
    user_url: 'https://github.com/SLywnow',
    image:"/images/hi-dark.webp",
    multipleBackgrounds:false,
  },
  {
    id: "ae7395ca-1555-4cf1-9a5d-fe637b31b1ec",
    name: 'refind-theme-regular-minimalism',
    description: "Another yet theme for rEFInd boot manager",
    link: 'https://github.com/Gutleibmann/refind-theme-regular-minimalism',
    user: 'Gutleibmann',
    user_url: 'https://github.com/Gutleibmann',
    image:"/images/minimalism.webp",
    multipleBackgrounds:false,
  },
  {
    id: "845f8f51-87b4-4511-bb5b-53ebf77f50f3",
    name: 'rEFInd-Metro',
    description: "rEFInd is a simplistic boot manager for UEFI based systems. This is a clean and minimal theme for it.",
    link: 'https://github.com/BetaTester41/rEFInd-Metro',
    user: 'BetaTester41',
    user_url: 'https://github.com/BetaTester41',
    image:"/images/metro.webp",
    multipleBackgrounds:false,
  },
  {
    id: "557ce9de-d1d0-41c8-9a20-ecdd47d10ec1",
    name: 'rEFInd-Phi',
    description: "rEFInd Phigros主题",
    link: 'https://github.com/zwzheng45/rEFInd-Phi',
    user: 'zwzheng45',
    user_url: 'https://github.com/zwzheng45',
    image:"/images/phi.webp",
    multipleBackgrounds:false,
  },
  {
    id: "f9c918f1-2b02-4180-9619-3a22e93ece07",
    name: 'rEFInd-Minimalist',
    description: "A rEFInd-Minimalist for rEFInd.",
    link: 'https://github.com/Nyoutaaa/rEFInd-Minimalist',
    user: 'Nyoutaaa',
    user_url: 'https://github.com/Nyoutaaa',
    image:"/images/minimalist.webp",
    multipleBackgrounds:false,
  },
];
