name: Find New rEFInd Themes (manual review)

on:
  schedule:
    - cron: "0 10 * * 1" # Every Monday at 10:00 UTC
  workflow_dispatch: # Optional manual trigger

jobs:
  find-new-themes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Generate new-themes-found.json
        run: |
          node <<EOF
          const fs = require('fs');
          const https = require('https');

          const query = encodeURIComponent("refind theme in:name,description");
          const url = `https://api.github.com/search/repositories?q=${query}&sort=updated&order=desc&per_page=10`;

          const options = {
            headers: {
              'User-Agent': 'GitHub Actions',
              'Accept': 'application/vnd.github.v3+json'
            }
          };

          https.get(url, options, (res) => {
            let data = "";
            res.on("data", chunk => data += chunk);
            res.on("end", () => {
              const json = JSON.parse(data);
              const themes = json.items.map(repo => ({
                name: repo.name,
                description: repo.description || "",
                link: repo.html_url,
                user: repo.owner.login,
                user_url: repo.owner.html_url,
                isNew: true
              }));

              fs.writeFileSync("new-themes-found.json", JSON.stringify(themes, null, 2));
              console.log("Saved new themes to new-themes-found.json");
            });
          }).on("error", err => {
            console.error("Error fetching from GitHub:", err.message);
          });
          EOF

      - name: Commit and push new JSON
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b update-new-themes-found
          git add new-themes-found.json
          git commit -m "📦 Add new-themes-found.json for review"
          git push origin update-new-themes-found

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update-new-themes-found
          title: "📦 New rEFInd themes found (manual review)"
          body: |
            This pull request includes a generated `new-themes-found.json` file with potential new rEFInd themes from GitHub.

            Please review and manually integrate valid entries into `src/data/themes.json`.
