name: Find new rEFInd themes

on:
  schedule:
    - cron: "0 12 * * 1" # Runs every Monday at noon
  workflow_dispatch: # Allows manual triggering

jobs:
  search:
    runs-on: ubuntu-latest
    steps:
      - name: Search GitHub for new rEFInd themes
        uses: actions/github-script@v7
        with:
          script: |
            const query = "refind theme in:name,description";
            const res = await github.search.repos({ q: query, sort: "updated", order: "desc" });

            const top5 = res.data.items.slice(0, 5).map(repo => `- [${repo.full_name}](${repo.html_url})`).join("\n");

            console.log("Found repositories:\n" + top5);

            await github.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "🔍 Weekly: New rEFInd themes found",
              body: "Here are the top 5 recently updated repositories:\n\n" + top5
            });
