- name: Commit and push if new themes found
  run: |
    git config user.name "github-actions[bot]"
    git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

    git fetch origin
    git checkout main
    git pull origin main
    git checkout -b ${{ steps.vars.outputs.branch_name }}

    if [ -f new-themes-found.json ]; then
      git status
      git diff --staged || true

      if git diff --cached --quiet; then
        echo "No changes detected in new-themes-found.json, skipping commit and push."
      else
        git add new-themes-found.json
        git commit -m "📦 New rEFInd themes found (manual review)"
        git push origin ${{ steps.vars.outputs.branch_name }}
      fi
    else
      echo "✅ No new themes found — skipping commit and push."
    fi
