name: Find and Propose New rEFInd Themes

on:
  schedule:
    - cron: "0 12 * * 1" # Every Monday at 12:00 UTC
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  find-themes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Generate dynamic branch name
        id: vars
        run: echo "branch_name=update-new-themes-$(date +'%Y%m%d-%H%M')" >> $GITHUB_OUTPUT

      - name: Run theme discovery script
        run: node scripts/findNewThemes.mjs

      - name: Commit and push if new themes found
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git fetch origin
          git checkout main
          git pull origin main
          git checkout -b ${{ steps.vars.outputs.branch_name }}

          if [ -f new-themes-found.json ]; then
            git add new-themes-found.json
            git commit -m "📦 New rEFInd themes found (manual review)"
            git push origin ${{ steps.vars.outputs.branch_name }}
          else
            echo "✅ No new themes found — skipping commit and push."
          fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.vars.outputs.branch_name }}
          title: "📦 New rEFInd themes found (manual review)"
          body: |
            This pull request includes a generated `new-themes-found.json` file with potential new rEFInd themes from GitHub.

            Please review and manually integrate valid entries into `src/data/themes.json`.
          commit-message: "📦 New rEFInd themes found (manual review)"
