name: Find and Propose New rEFInd Themes

on:
  schedule:
    - cron: "0 12 * * 1" # Every Monday at 12:00 UTC
  workflow_dispatch:

jobs:
  find-themes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies (if needed)
        run: |
          mkdir -p scripts
          echo "// placeholder" > scripts/findNewThemes.mjs

      - name: Run theme discovery script
        run: node scripts/findNewThemes.mjs

      - name: Commit and push if new themes found
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b update-new-themes-found
          git add new-themes-found.json || echo "No new themes found."
          git diff --cached --quiet || git commit -m "📦 New rEFInd themes found (manual review)" && git push origin update-new-themes-found

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update-new-themes-found
          title: "📦 New rEFInd themes found (manual review)"
          body: |
            This pull request includes a generated `new-themes-found.json` file with potential new rEFInd themes from GitHub.

            Please review and manually integrate valid entries into `src/data/themes.json`.
          commit-message: "📦 New rEFInd themes found (manual review)"
